-- Projeto Físico (Script SQL)

CREATE TABLE IF NOT EXISTS CLIENTE (
    COD_CLIENTE     INT             NOT NULL,
    NOM_CLIENTE     VARCHAR(100)    NOT NULL,
    RUA_CLIENTE     VARCHAR(100)    NOT NULL,
    NUM_CLIENTE     VARCHAR(15)     NOT NULL,
    PRIMARY KEY     (COD_CLIENTE)     
);

CREATE TABLE IF NOT EXISTS TELEFONE_CLIENTE (
    COD_CLIENTE     INT             NOT NULL,
    TEL_CLIENTE     VARCHAR(11)     NOT NULL,
    PRIMARY KEY (COD_CLIENTE, TEL_CLIENTE),
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

CREATE TABLE IF NOT EXISTS EMAIL_CLIENTE (
    COD_CLIENTE     INT             NOT NULL,
    EMAIL_CLIENTE   VARCHAR(15)     NOT NULL,
    PRIMARY KEY (COD_CLIENTE, EMAIL_CLIENTE),
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

CREATE TABLE IF NOT EXISTS VENDA (
    NUM_PEDIDO      INT             NOT NULL,
    DTA_PEDIDO      DATE            NOT NULL,
    COD_CLIENTE     INT             NOT NULL,
    PRIMARY KEY (NUM_PEDIDO),
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    COD_PRODUTO     INT             NOT NULL,
    NOM_PRODUTO     VARCHAR(100)    NOT NULL,
    EST_PRODUTO     INT             DEFAULT 0,
    PCO_PRODUTO     DECIMAL(10,2)   DEFAULT 0,
    FABRICANTE      VARCHAR(100)    NOT NULL,
    PRIMARY KEY (COD_PRODUTO)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
    COD_FORNECEDOR  INT             NOT NULL,
    NOM_FORNECEDOR  VARCHAR(100)    NOT NULL,
    RUA_FORNECEDOR  VARCHAR(100)    NOT NULL,
    NUM_FORNECEDOR  VARCHAR(15)     NOT NULL,
    PRIMARY KEY (COD_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS TELEFONE_FORNECEDOR (
    COD_FORNECEDOR INT              NOT NULL,
    TEL_FORNECEDOR VARCHAR(11)      NOT NULL,
    PRIMARY KEY (COD_FORNECEDOR, TEL_FORNECEDOR),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR (COD_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS EMAIL_FORNECEDOR (
    COD_FORNECEDOR INT              NOT NULL,
    EMAIL_FORNECEDOR VARCHAR(15)    NOT NULL,
    PRIMARY KEY (COD_FORNECEDOR, EMAIL_FORNECEDOR),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR (COD_FORNECEDOR)  
);

CREATE TABLE IF NOT EXISTS COMPRA (
    NUM_PEDIDO      INT             NOT NULL,
    DTA_PEDIDO      DATE            NOT NULL,
    COD_FORNECEDOR  INT             NOT NULL,
    PRIMARY KEY     (NUM_PEDIDO),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR (COD_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS PEDIDO_ESTA_COMPRA (
    NUM_PEDIDO      INT             NOT NULL,
    COD_PRODUTO     INT             NOT NULL,
    PRIMARY KEY (NUM_PEDIDO, COD_PRODUTO),
    FOREIGN KEY (NUM_PEDIDO) REFERENCES COMPRA (NUM_PEDIDO),
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);

CREATE TABLE IF NOT EXISTS VENDA_CONTEM_PRODUTO (
    NUM_PEDIDO      INT             NOT NULL,
    COD_PRODUTO     INT             NOT NULL,
    PCO_PRODUTO     DECIMAL(10,2)   DEFAULT 0,
    QTD_PRODUTO     INT             DEFAULT 0,
    PRIMARY KEY  (NUM_PEDIDO, COD_PRODUTO),
    FOREIGN KEY  (NUM_PEDIDO) REFERENCES VENDA (NUM_PEDIDO),
    FOREIGN KEY  (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)     
);

CREATE TABLE IF NOT EXISTS VENDA_CONTEM_PRODUTO (
    NUM_PEDIDO      INT             NOT NULL,
    COD_FORNECEDOR  INT             NOT NULL,
    PCO_PRODUTO     DECIMAL(10,2)   DEFAULT 0,
    QTD_PRODUTO     INT             DEFAULT 0,
    PRIMARY KEY (NUM_PEDIDO, COD_PRODUTO),
    FOREIGN KEY (NUM_PEDIDO) REFERENCES VENDA (NUM_PEDIDO),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR (COD_FORNECEDOR)
);
